s/Linux-Mandrake/Mandrake Linux/ s/linux-mandrake/mandrakesoft/ (hand made, no i18n messages done)
git-svn-id: svn+ssh://svn.mandriva.com/svn/soft/drakx/trunk@195786 99302b65-d5f7-0310-b3dd-f8cd6f4e3d94

diff --git a/live_update b/live_update
--- a/live_update
+++ b/live_update
@@ -8,11 +8,11 @@ if [ "$UID" -ne 0 ]; then
     if [ -x "$message" ]; then
 	case "$LANG" in
 	    fr*) buttons="Arrêter:0"
-		 msg="Mise à jour en direct de Linux-Mandrake.
+		 msg="Mise à jour en direct de Mandrake Linux.
 
 Vous devez être l'utilisateur root pour lancer cette application." ;;
 	    *) buttons="Abort:0"
-	       msg="Linux-Mandrake live upgrade.
+	       msg="Mandrake Linux live upgrade.
 
 You need to be root to start this program." ;;
 	esac
@@ -31,17 +31,17 @@ if [ ! -x "$distrib/Mandrake/mdkinst/usr/bin/perl-install/live_install" ]; then
     if [ -x "$message" ]; then
 	case "$LANG" in
 	    fr*) buttons="Arrêter:0"
-		 msg="Mise à jour en direct de Linux-Mandrake.
+		 msg="Mise à jour en direct de Mandrake Linux.
 
-Impossible de trouver le Cédérom d'installation de Linux-Mandrake dans le premier lecteur." ;;
+Impossible de trouver le Cédérom d'installation de Mandrake Linux dans le premier lecteur." ;;
 	    *) buttons="Abort:0"
-	       msg="Linux-Mandrake live upgrade.
+	       msg="Mandrake Linux live upgrade.
 
-Unable to find Linux-Mandrake Installation Cd-Rom in the first drive." ;;
+Unable to find Mandrake Linux Installation Cd-Rom in the first drive." ;;
 	esac
 	$message -buttons "$buttons" -print "$msg"
     else
-	echo >&2 "Unable to find Linux-Mandrake Installation Cd-Rom in the first drive."
+	echo >&2 "Unable to find Mandrake Linux Installation Cd-Rom in the first drive."
     fi
     exit 2
 fi
@@ -49,14 +49,14 @@ fi
 if [ -x "$message" ]; then
     case "$LANG" in
 	fr*) buttons="Mise à jour:0,Annuler:1"
-	     msg="Mise à jour en direct de Linux-Mandrake.
+	     msg="Mise à jour en direct de Mandrake Linux.
 
 Appuyez sur \"Mise à jour\" pour lancer la mise à jour de votre système,
 cela prendra quelques minutes avant que l'écran de DrakX apparaisse.
 
 Appuyez sur \"Annuler\" pour ne pas mettre à jour votre système de cette manière." ;;
 	*) buttons="Upgrade:0,Cancel:1"
-	   msg="Linux-Mandrake live upgrade.
+	   msg="Mandrake Linux live upgrade.
 
 Press \"Upgrade\" to start live upgrade on your system, note this will
 take some time to prepare the system before DrakX screen appears.
