add a check
git-svn-id: svn+ssh://svn.mandriva.com/svn/soft/drakx/trunk@212041 99302b65-d5f7-0310-b3dd-f8cd6f4e3d94

diff --git a/rescue/make_partimage_save_rest_all b/rescue/make_partimage_save_rest_all
--- a/rescue/make_partimage_save_rest_all
+++ b/rescue/make_partimage_save_rest_all
@@ -17,6 +17,10 @@ if [ -n "$partimage_dir" ]; then
 	echo "can't find $partimage_dir$local_where"
 	exit 1
     }
+    [ -r "$partimage_dir$local_where/lst" ] || {
+	echo "can't read $partimage_dir$local_where/*"
+	exit 1
+    }
 fi
 
 rm -rf .tmp
