Author: alien <alien@5b7c3c08-40e5-403b-9995-ace06908e4af> Date:   Sat Feb 25 20:52:44 2012 +0000
    add some tests and error handling in startssh



git-svn-id: svn+ssh://svn.mandriva.com/svn/soft/drakx/trunk@274260 99302b65-d5f7-0310-b3dd-f8cd6f4e3d94

diff --git a/rescue/startssh b/rescue/startssh
--- a/rescue/startssh
+++ b/rescue/startssh
@@ -1,20 +1,27 @@
 #!/bin/bash
 
-passwd=`genpasswd`
+# test for an up interface != lo
+if test "x"`ifconfig | cut -d ' ' -f 1 | grep -v '^$' | grep -v lo` = "x"; then
+	echo "There is no up interface, you can try to execute 'drvinst' to find drivers and 'dhcp-client' to configure your interface for DHCP." >&2
+	exit 5
+fi
 
+# generate host keys
+mkdir -p /etc/dropbear
+[[ -f /etc/dropbear/dropbear_dss_host_key ]] || dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key >/dev/null || { echo "Can't generate dsa host key" >&2 ; exit 4 }
+[[ -f /etc/dropbear/dropbear_rsa_host_key ]] || dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key >/dev/null || { echo "Can't generate rsa host key" >&2 ; exit 3 }
+
+# set a password
+passwd=`genpasswd`
 if (( $? != 0 )); then
 	reset
 	exit $?
 fi
+sed -E -i -e 's/^root:[^:]*:/root:'"$passwd"':/' /etc/passwd || { echo "Can't set password" >&2 ; exit 2 }
 
-# change passwd file
-sed -E -i -e 's/^root:[^:]*:/root:'"$passwd"':/' /etc/passwd
-
-# generate host keys
-mkdir -p /etc/dropbear
-[[ -f /etc/dropbear/dropbear_dss_host_key ]] || dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key >/dev/null
-[[ -f /etc/dropbear/dropbear_rsa_host_key ]] || dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key >/dev/null
+# test for /dev/pts
+grep '^devpts /dev/pts devpts ' /proc/mounts >/dev/null 2>/dev/null || mount -t devpts devpts /dev/pts
 
 echo ""
 echo -n "Starting ssh daemon... "
-dropbear -E 2>/var/log/dropbear.log && echo "OK"
+dropbear -E 2>/var/log/dropbear.log && echo "OK" || { echo "Failed" ; exit 1 }
