drop deprecated (& redundant) -E argument to sed
git-svn-id: svn+ssh://svn.mandriva.com/svn/soft/drakx/trunk@274590 99302b65-d5f7-0310-b3dd-f8cd6f4e3d94

diff --git a/rescue/startssh b/rescue/startssh
--- a/rescue/startssh
+++ b/rescue/startssh
@@ -17,7 +17,7 @@ if (( $? != 0 )); then
 	reset
 	exit $?
 fi
-sed -E -i -e 's/^root:[^:]*:/root:'"${passwd//\//\\/}"':/' /etc/passwd || { echo "Can't set password" >&2 ; exit 2; }
+sed -i -e 's/^root:[^:]*:/root:'"${passwd//\//\\/}"':/' /etc/passwd || { echo "Can't set password" >&2 ; exit 2; }
 
 # test for /dev/pts
 grep '^devpts /dev/pts devpts ' /proc/mounts >/dev/null 2>/dev/null || mount -t devpts devpts /dev/pts
