fix dropbear startssh script to work with busybox
git-svn-id: svn+ssh://svn.mandriva.com/svn/soft/drakx/trunk@274938 99302b65-d5f7-0310-b3dd-f8cd6f4e3d94

diff --git a/rescue/startssh b/rescue/startssh
--- a/rescue/startssh
+++ b/rescue/startssh
@@ -1,4 +1,6 @@
-#!/bin/bash
+#!/bin/sh
+
+. /etc/init.d/functions
 
 # test for an up interface != lo
 if test "x"`ifconfig | cut -d ' ' -f 1 | grep -v '^$' | grep -v lo` = "x"; then
@@ -8,17 +10,17 @@ fi
 
 # generate host keys
 mkdir -p /etc/dropbear
-[[ -f /etc/dropbear/dropbear_dss_host_key ]] || dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key >/dev/null || { echo "Can't generate dsa host key" >&2 ; exit 4; }
-[[ -f /etc/dropbear/dropbear_rsa_host_key ]] || dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key >/dev/null || { echo "Can't generate rsa host key" >&2 ; exit 3; }
+[ -f /etc/dropbear/dropbear_dss_host_key ] || dropbearkey -t dss -f /etc/dropbear/dropbear_dss_host_key >/dev/null || { echo "Can't generate dsa host key" >&2 ; exit 4; }
+[ -f /etc/dropbear/dropbear_rsa_host_key ] || dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key >/dev/null || { echo "Can't generate rsa host key" >&2 ; exit 3; }
 
 # set a password
-passwd=`genpasswd`
-if (( $? != 0 )); then
+echo "Give a password:"
+passwd=`mkpasswd | grep -v Password:`
+if [ $? != 0 ]; then
 	reset
 	exit $?
 fi
-sed -i -e 's/^root:[^:]*:/root:'"${passwd//\//\\/}"':/' /etc/passwd || { echo "Can't set password" >&2 ; exit 2; }
+sed -e 's#^root:[^:]*:#root:'"${passwd}"':#' -i /etc/passwd || { echo "Can't set password" >&2 ; exit 2; }
 
 echo ""
-echo -n "Starting ssh daemon... "
-dropbear -E 2>/var/log/dropbear.log && echo "OK" || { echo "Failed" ; exit 1; }
+action "Starting ssh daemon... " dropbear -E 2>/var/log/dropbear.log
