*** empty log message ***
git-svn-id: svn+ssh://svn.mandriva.com/svn/soft/drakx/trunk@193087 99302b65-d5f7-0310-b3dd-f8cd6f4e3d94

diff --git a/tools/make_mdkinst_stage2 b/tools/make_mdkinst_stage2
--- a/tools/make_mdkinst_stage2
+++ b/tools/make_mdkinst_stage2
@@ -13,12 +13,12 @@ REP4PMS=/usr/bin/perl-install
 DEST=$1
 STAGE2=$2
 
-testandset() { [ -x $1/build_archive ] && BUILD_ARCHIVE=$1/build_archive; }
+testandset() { [ -x $1/packdrake ] && BUILD_ARCHIVE=$1/packdrake; }
 testandset `pwd`/misc
 testandset `pwd`/.
 testandset /$DEST/../../misc
 testandset `pwd`/$DEST/../../misc
-[ -z "$BUILD_ARCHIVE" ] && { echo "can't find build_archive"; exit 1; }
+[ -z "$BUILD_ARCHIVE" ] && { echo "can't find packdrake"; exit 1; }
 
 if [ $EUID != "0" ]; then
     SUDO="sudo"
@@ -44,12 +44,12 @@ rm -f $STAGE2TMP/$REP4PMS/po/DrakX.pot
 #done
 for i in /usr/share/locale; do
     name=`basename $i`
-    (cd $STAGE2TMP/$i ; find * | $BUILD_ARCHIVE ../$name.cz2 4000000)
+    (cd $STAGE2TMP/$i ; find * | $BUILD_ARCHIVE -b9s ../$name.cz2 4000000)
     rm -rf $STAGE2TMP/$i
 done
 for i in /usr/share/keymaps /usr/share/xmodmap $REP4PMS/po; do
     name=`basename $i`
-    (cd $STAGE2TMP/$i ; ls * | $BUILD_ARCHIVE ../$name.cz2 400000)
+    (cd $STAGE2TMP/$i ; ls * | $BUILD_ARCHIVE -b9s ../$name.cz2 400000)
     rm -rf $STAGE2TMP/$i
 done
 
