- ensure failing to build mdkinst.sqfs is a fatal error
git-svn-id: svn+ssh://svn.mandriva.com/svn/soft/drakx/trunk@232456 99302b65-d5f7-0310-b3dd-f8cd6f4e3d94

diff --git a/tools/mdkinst_stage2_tool b/tools/mdkinst_stage2_tool
--- a/tools/mdkinst_stage2_tool
+++ b/tools/mdkinst_stage2_tool
@@ -36,7 +36,7 @@ if [ $ACTION = "--compress" ]; then
     [ -d "$LIVE_DIR" ] || error
     echo "Creating $COMPRESSED_IMAGE from $LIVE_DIR"
     rm -f $STAGE2_DIR/.room
-    mksquashfs $LIVE_DIR $COMPRESSED_IMAGE -all-root -noappend >/dev/null
+    mksquashfs $LIVE_DIR $COMPRESSED_IMAGE -all-root -noappend >/dev/null || { echo "mksquashfs failed"; exit 1; }
     chmod 755 $COMPRESSED_IMAGE
     echo foo > $STAGE2_DIR/.room
     if [ -s $STAGE2_DIR/.room ]; then
